/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jackcompiler
import java.nio.file.Files
import java.nio.file.Paths



fun main(args: Array<String>) {
    analyzer(args[0])
//    val outputT = File("../ArrayTest/MainToken.xml")
}

fun analyzer(path: String) {
    Files.walk(Paths.get(path))
        .filter {
            it.toString().endsWith(".jack")
        }
        .forEach {
            println(it.toString())
            val tokenizer = JackTokenizer(it.toString())
            while (tokenizer.hasMoreTokens()) {
                tokenizer.advance()
            }
        }
//    val outputT = File("../ArrayTest/MainToken.xml")
}


