/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jackcompiler
import java.nio.file.Files
import java.nio.file.Paths



fun main(args: Array<String>) {
    analyzer(args[0])
}

fun analyzer(path: String) {
    Files.walk(Paths.get(path))
        .filter {
            it.toString().endsWith(".jack")
        }
        .forEach {
            println(it.toString())
            val tokenizer = JackTokenizer(it.toString())
            while (tokenizer.hasMoreTokens()) {
                tokenizer.advance()
            }
            CompilationEngine(it.toString().replace(".jack", "T.xml"), it.toString().replace(".jack", "Final.xml"))
        }
}


