/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jackcompiler

fun main() {
    var tokenizer = JackTokenizer("../ArrayTest/Main.jack")
    while (tokenizer.hasMoreTokens()) {
        tokenizer.advance()
    }
}
